### ISSUE TITLE
Enum-like points for MoveMouse task

### ISSUE THREAD

**Issue by devahmedshendy** [0xLeif/SwiftRobot#4]
App related points: .center, .top, .bottom, .leading or .left, .trailing or .right

```swift
MoveMouse(to: .top)
```
Screen related points: .screenCenter, .screenTop, .screenBottom, .screenLeading or .screenLeft, .screenTrailing or .screenRight

```swift
MoveMouse(to: .screenBottom)
```

**Comment by 0xLeif** [comment]
> App related points: .center, .top, .bottom, .leading or .left, .trailing or .right

Should the app related points default to screen related points if the application doesn't have a window like a command line app?

**Comment by devahmedshendy** [comment]
> Should the app related points default to screen related points if the application doesn't have a window like a command line app?

Yeah, good point.

**Comment by devahmedshendy** [comment]
@0xLeif RobotKit is built for English language, so we will stick for now to left/right naming? and maybe later if we will add support for RTL language, we may introduce the structure that supports the naming of leading/trailing concept? what do you think?

**Comment by 0xLeif** [comment]
Good point! Right now let's stick with English... but I think we can plan to add localization later on.
